### PR TITLE
Add PBR tutorial

### PR DESCRIPTION
**Pull request by javagl**
The original author confirmed that it is OK to merge this back into the official Khronos repository.

As soon as this is merged, the link at https://github.com/KhronosGroup/glTF/blob/master/README.md#tutorials can be updated to point to the Khronos version.

### CODE REVIEW

**Comment by javagl** [comment]
OK, not sure how to handle the CLA here. @moneimne would probably sign it, and I vaguely remember that @pjcozzi once also did one or another thing for glTF ;-) If somebody is confident that this is OK, it could be merged, otherwise I'd wait or reach out for the CLA signing.

**Comment by pjcozzi** [comment]
@Khronoswebmaster can you please confirm how CLAs work nowadays with Khronos?  Or is the GitHub terms of service enough?

**Comment by neiltrevett** [comment]
ALL contributions, at a minimum, must be covered by the contributor executing the click-through CLA on the repo to which they are contributing.  Khronos Members that wish to, may execute the [Khronos Corporate CLA Agreement,](https://members.khronos.org/wg/General/document/previewpdf/928) so they have a written agreement that supersedes the click-through CLA. 

If we are taking contributions from non-members into ratified specifications - there are  guidelines on non-member Contributions [here](https://members.khronos.org/wg/General/document/previewpdf/930) - but this seems to be a tutorial - so the IP risk is very low.

**Comment by Khronoswebmaster** [comment]
The exception is CC-BY, for which we have no CLA. @neiltrevett will correct me if I am wrong, but I believe CC-BY contributor license agreement is covered fairly well under the GitHub ToS.

**Comment by Khronoswebmaster** [comment]
A small caveat some folks run into is pushing a PR to GitHub using a different email address than that used in their GitHub account. In order to sign a CLA in this case, the user will need to add their alternative email address to their profile.

**Comment by neiltrevett** [comment]
Thanks James - I should have looked more at the context before diving in - my comments above about needing a CLA and the option of a corporate CLA apply to repos containing software under Apache 2.0. For repos under CC-BY we do indeed use "Inbound=Outbound" and so an explicit CLA is not needed. 

BUT I couldn't find a License here on the glTF-Tutorials repository. As this repo does not contain software, I suggest we add the CC-BY license using REUSE (as https://github.com/KhronosGroup/OpenCL-Guide for example) and then we can accept contributions without an explicit CLA.

**Comment by javagl** [comment]
A PR for adding the CC-BY 4.0 license is at https://github.com/KhronosGroup/glTF-Tutorials/pull/47 . 
If everybody agrees, this could be merged. 

(I'm not sure whether it will be necessary to disable the CLA check then, or whether this happens automatically via GitHub magic)

After that, the PBR tutorial could be merged as well.

**Comment by outofcontrol** [comment]
@javagl Would it be possible to run [REUSE lint](https://reuse.software) on this repository and verify that all is well setup, and then create a PR with those files? A separate license in the root is also beneficial to ensure that GitHub recognizes the license as well.

**Comment by outofcontrol** [comment]
> (I'm not sure whether it will be necessary to disable the CLA check then, or whether this happens automatically via GitHub magic)

CLA has been disabled as we are covered with inbound=outbound. The CC-BY is a good addition to ensure everyone is clear on the license.

**Comment by javagl** [comment]
@outofcontrol Yet another tool. Not sure what this is supposed to do, but I'm not sure if/when I find time to look into that. In doubt, we might as well keep the link to the original PBR tutorial and *not* merge it back into this one.

**Comment by outofcontrol** [comment]
Don't worry about, I can lint the repository once the PR for CC-BY is accepted.

**Comment by Khronoswebmaster** [comment]
It would appear that a PR created when CLA-Assistant was enabled, needs to be removed and resubmitted to clear the Status. AFAIK GitHub offers no way to manually change the status on the PR. CLA-Assistant is now been disabled and the webhook for this repository has been removed, so it should be safe to proceed with a new PR. Apologies for this issue.

**Comment by javagl** [comment]
OK, if nobody screams "STOP!", then I'd ...

- merge the PR of the CC-BY license at https://github.com/KhronosGroup/glTF-Tutorials/pull/47 soon
- trigger outofcontrol for this linting thing (I've only skimmed it - to my understanding, this will still be a manual process, because we can't put license headers in files, so we'll just place a `*` wildcard somewhere and be all good, right?)
- Close this PR, and re-open it

**Comment by javagl** [comment]
@outofcontrol The license PR has been merged, but I haven't yet looked at what else has to be done for REUSE. In doubt, I'd try to allocate some time for that later.

**Comment by outofcontrol** [comment]
Unfortunately this PR would need to be resubmitted as a new PR in order for it to be accepted. CLA-assistant and GitHub give us no way alter the status of PR, which means this PR is blocked.

> It would appear that a PR created when CLA-Assistant was enabled, needs to be removed and resubmitted to clear the Status. AFAIK GitHub offers no way to manually change the status on the PR. CLA-Assistant is now been disabled and the webhook for this repository has been removed, so it should be safe to proceed with a new PR. Apologies for this issue.

**Comment by javagl** [comment]
Sorry, I should have been more precise here, but that's what I meant when I said "re-open". If you do this lint thing, just give me a `@ping`, otherwise, I may look at this maybe during the weekend.

**Comment by javagl** [comment]
@outofcontrol This was buried under other tasks. 

So to be specific: Will you set up the REUSE thing? 

If nobody else will do it, I'd have a look. But I wonder: Is the goal to generate some file that tells REUSE to just ~"ignore everything, because this is not code"? According to the REUSE site, one could/should also add copyright headers to markdown files, with *"with corresponding comment syntax"* - which does not exist. It could be `<!-- html comments -->` , which happen to work at GitHub, but are not really markdown. Neither seems to make very much sense for me...

**Comment by outofcontrol** [comment]
Create new PR https://github.com/KhronosGroup/glTF-Tutorials/pull/52 with a compliant REUSE setup. Once reviewed we should be set.

**Pull request closed without merging**
