### PR TITLE
Initial commit - Blender glTF converter

### PR DESCRIPTION
**Pull request by prnikiel**
Initial take on the example glTF converter using Blender. The script is an example and is designed as a boilerplate / simple guide to create automation tools, rather than a production-ready tool.

### CODE REVIEW

**Comment by javagl** [comment]
I created a PR at https://github.com/prnikiel/glTF-Tutorials/pull/1 with some **suggestions** for changes (direct preview at https://github.com/javagl/glTF-Tutorials/tree/blender-gltf-converter-fixes/BlenderGltfConverter ).

(**Iff** you agree to the changes, the process could then be: You could merge this other PR into _your_ repository. This will automatically update _this_ PR, which could then be merged into the Khronos repository)

---

The other PR extends the `README.md` quite a bit, with some introductory text and explainations e.g. of the command line parameters and customization options. 

It's hard to decide where to put this information: It should be in the `README.md` to be easily accessible and nicely formatted. But assuming that people are _supposed_ to just copy the `.py` file and use it as a template, _some_ of this information should also be retained as comments in the script itself, even if it may appear to be 'redundant' at the first glance.

I tried to not _technically_ modify the script itself (minor tweaks for the comments), with one exception: 

When I tried this out with a 'suzanne.obj' file and a freshly installed Blender 3.2, then the export contained some cube:

BlenderBox

I think this is the 'Default Cube' that is part of the 'default scene' of blender. I inserted 

    # Remove the 'Cube' that is part of the default scene
    bpy.context.scene.objects["Cube"].select_set(True);
    bpy.ops.object.delete()

into the script, but I'm **not** a Blender expert, so I'm not sure whether this is the right thing to to here. (I'd just like to avoid confusion for others, who might observe the same effect...)

**Comment by javagl** [comment]
Just a short ping @prnikiel :  There was some discussion about the suggested code change for removing the Cube (IIRC it should just clear the whole scene instead), and about a wording issue in my suggested change (related to ~"default Blender settings") - did you have a chance to look at this? 

(Otherwise, I'd try to update my PR to change the code, and to and restore your original wording for the default settings ASAP)

**Comment by prnikiel** [comment]
Hi,
I’m currently on holiday. As I mentioned during tooling tsg, after your
suggestion on the cube I actually changed it to clear the whole scene in my
original repo. I didn’t do it in this one yet. If this is very urgent I can
look into it during weekend, if not I’ll do that after I’m back at work
(8th August).
Kind Regards,
Paweł

W dniu czw., 28.07.2022 o 16:52 Marco Hutter ***@***.***>
napisał(a):

**Comment by prnikiel** [comment]
> Embarassingly, despite quite a while of searching, I did not find this 'Info window' - is it possible to add more details here, for Blender-noobs like me?

Every window in Blender has a small dropdown in the upper right corner that allows you to change the window type to any other window type. This is basic Blender UI knowledge and IMO is beyond instructions for this repo. But I can add it if you feel strongly about this one.

**Comment by javagl** [comment]
The updated state looks fine for me (I didn't do another "deep" proofreading pass, but think that it largely integrated the suggestions and addressed the points from the previous comments). 

Two small things:

- There's still that `.gitignore` file that shouldn't be there...
- There should be an entry in the main README at https://github.com/prnikiel/glTF-Tutorials/blob/blender-gltf-converter/README.md for that new tutorial

**Comment by prnikiel** [comment]
OK I'll adjust that now. What's wrong with having `.gitignore` though?

**Comment by javagl** [comment]
> What's wrong with having .gitignore though?

I think that it did not really serve any purpose here. I don't see why the tutorial directory should contain any files that should be ignored by Git...

**Comment by javagl** [comment]
I _have_ to add this outtake here: 

glTFTutorialsLanguage

The glTF tutorials are now primarily written in Python 😆

**Comment by prnikiel** [comment]
> I _have_ to add this outtake here:
> 
> glTFTutorialsLanguage
> 
> The glTF tutorials are now primarily written in Python 😆

LOVE IT 😆

**Pull request merged**
