### PR TITLE
Add PBR tutorial - updated

### PR DESCRIPTION
**Pull request by javagl**
This replaces https://github.com/KhronosGroup/glTF-Tutorials/pull/46 , now that the CLA handling should be set up correctly.

As soon as this is merged, the link at https://github.com/KhronosGroup/glTF/blob/master/README.md#tutorials can be updated to point to the Khronos version.

### CODE REVIEW

**Comment by javagl** [comment]
@Khronoswebmaster I thought (based on https://github.com/KhronosGroup/glTF-Tutorials/pull/46#issuecomment-813432804 ) that it should now no longer show the CLA as a pending check - did I misunderstand something here?

**Comment by Khronoswebmaster** [comment]
I will contact cla-assistant and see how we fix this. This repository is not linked to cla-assistant and there are no webhooks, but still it is attempting to approve this. Clicking the Details link beside cla-assistant in this repository shows this error:

    There is no CLA to sign for KhronosGroup/glTF-Tutorials

**Comment by javagl** [comment]
If this is the easiest solution, I can also close this PR and open it as a new one (that is: *if* the current issue might only be a glitch to some settings being changed *while* this PR was open, and *if* this issue does not affect future PRs). Just drop me a note if I should try it.

**Comment by Khronoswebmaster** [comment]
If you create a new PR, does it still show the CLA. This would be interesting to find out. The fact these PRs are stuck with still having the CLA enabled worries me that new PRs will also have the CLA enabled.

**Pull request closed without merging**
