### PR TITLE
Update gltfTutorial_020_Skins.md

### PR DESCRIPTION
**Pull request by Makogan**
The table and the english don' t agree, the edited table is what I see when I load the data on my end.

### CODE REVIEW

**Comment by javagl** [comment]
Thanks for the contribution. But in this case, the *text* was wrong and the *table* was correct. This was recently fixed in https://github.com/KhronosGroup/glTF-Tutorials/pull/40/ . I have updated the text via https://github.com/KhronosGroup/glTF-Tutorials/pull/42

But **important**, to be sure: You said 

>  the edited table is what I see when I load the data on my end.

Does this refer to the [data from the "SimpleSkin" section](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_019_SimpleSkin.md#a-simple-skin), or to the [SimpleSkin sample model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleSkin)? 

The data in the tutorial section has not been updated yet. I'll prepare this now. If you can confirm that you used this data, then I'll update it ASAP (and apologies for the possible confusion in this case)

**Comment by Makogan** [comment]
I am talking about the data from the gltf model itself. i.e. the data in the json when you download the sample models repo.

**Comment by javagl** [comment]
@Makogan I just had another look at the data that is stored in this model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleSkin/glTF-Embedded (as well as the non-embdeed one),

And it appears to have the right indices:

SimpleSkin001

Of course, this *could* just be a bug on my side. So I also looked at the actual glTF file:

- The data is accessed with `accessor[2]`, which uses a `VEC4` of `GL_UNSIGNED_SHORT`
- This accessor refers to `bufferView[2]` (which as a `byteStride` of 16)
- This buffer view directly refers to `buffer[1]`, without any offset

And this is the data that is contained in the `bin` file, compared to the data layout image that is shown at the SimpleSkin page: The marked part should match the element where the mouse cursor is, and it should contain `0` at this place:

SimpleSkin002

Can you point to the tool/library that caued you to see the `1` at this point?

**Comment by Makogan** [comment]
This is the file I am using: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/SimpleSkin/glTF/SimpleSkin.gltf

I am loading the gltf file using tinygltf. And extracting the values with my own code. Although a bug is always possible I don;t think it is. I have a single subroutine to load values from accessors, and so far it has worked for the triangle examples, the morph cube and morph sphere. So it would be weird that the subroutine works for every other case but somewhat fails for this one.

I can go and verify with a tool, what can i do to inspect the loaded values on linux?

**Comment by javagl** [comment]
I don't know a tool that can easily display the "extracted" data of an `accessor` (except for my [JglTF browser](https://github.com/javagl/JglTF/tree/master/jgltf-browser) , which I used to make the first screenshot). The babylon sandbox at https://sandbox.babylonjs.com/ has a pretty hidden debug setting, "Display Skeletonmap", which looks like it *might* be a visualization of what we're looking for, but may not be sufficient to be sure here.

However, one *crucial* difference between the models that you mentioned and the `SimpleSkin` example is that the `bufferView` in the latter has a (non-zero) `byteStride` value. 

Do you take into account the `byteStride` when you load the values? 

(It wouldn't exactly explain why you see `0 1 0 0` - I'd rather expect **all** values to be `0 0 0 0` if you did not consider it - but that might be a point to look into...)

**Comment by javagl** [comment]
@Makogan Update - I knew that VS Code has a glTF plugin, but had not used it extensively, and wasn't sure whether it could show the accessor data. But it can: You can load the glTF asset, right-click on the `accessor` and select "Inspect Data", and it will show the accessor data in the panel on the left:

SimpleSkin003

(And yes, the result is the same there: It shows `0 0 0 0` for the relevant accessor...)

**Comment by Makogan** [comment]
I swear I am not trolling this is what I see on my end:
image

**Comment by Makogan** [comment]
Wait when was this changed, I downloaded the examples last week, I am doing a git diff just to check and my files are different to what is on the remote.

**Comment by Makogan** [comment]
So I have got no idea how, but a bunch of files in the downloaded models repo I had were different? I did a git diff and stuff was added, however the repo was up to date. I don;t think I ever touched the files myself? On any case, i did git stash and now my local results agree with what is being described here. Weird stuff.

**Comment by javagl** [comment]
Sounds like a git/version glitch then (maybe you downloaded an old version of a non-up-to-date fork or so?). 

If it's not OK to close this, just drop me a note.

**Pull request closed without merging**
