### PR TITLE
Removed GL_ prefixes from enums

### PR DESCRIPTION
**Pull request by sjfricke**
There are no `GL_` prefixes in the glTF spec

### CODE REVIEW

**Comment by javagl** [comment]
On one hand, that's a valid point. On the other hand, I intentionaly used these prefixes, to make clear that these indeed correspond to the GL constants. (It may depend on the context where glTF is used: In WebGL, there are no `GL_` prefixes, whereas in OpenGL, they are present).

@pjcozzi  and maybe @lexaknyazev : Is there a "policy" or "guideline" for this? It could be justified to align the names with those that are used in the spec. But maybe it should somehow be made clear that glTF did not make these up, but that they are the same constants that already are defined (with or without the `GL_` prefix) in every GL-based environment.

(If this is merged, I'll also have to update the PNGs for the affected SVG files)

**Comment by lexaknyazev** [comment]
`GL_` prefix gives a hint that integer values match OpenGL headers. Imo, this becomes less relevant with modern APIs. 

Also there was some criticism about using GL-based enums in the first place. In the JS world, enums have string form (better readability), while newer native APIs (e.g. Vulkan) tend to use small consequential integers with separated scopes for each parameter (partly to avoid switch-case at runtime).

My only suggestion about this issue wrt glTF 2.0 is to keep things consistent across all the docs.

**Comment by javagl** [comment]
Since the spec does **not** use the `GL_`-prefix, this means that this PR should be merged. However, I'll leave it unmerged/open for now, until I can also update the images and (possibly do another full-text search for `GL_`, just in case). 

<sub>(Now I wonder whether I should also update the glTF-Overview, but that's probably a different story...)</sub>

**Comment by pjcozzi** [comment]
> (Now I wonder whether I should also update the glTF-Overview, but that's probably a different story...)

I think we should consistently remove `GL_` throughout - so I would say yes...when you have time.

**Pull request merged**
