### PR TITLE
Rename gltfTutorial directory to docs

### PR DESCRIPTION
**Pull request by outofcontrol**
Github allows hosting files in `/docs` as a website. Renamed `/gltfTutorial` directory to simplify hosting these tutorials on GitHub and mirroring to https://khronos.org/gltf/tutorials.

### CODE REVIEW

**Comment by javagl** [comment]
Is the main purpose of that to simplify the mapping to https://khronos.org/gltf/tutorials ? 

(Specifically: I thought that the version at https://github.khronos.org/glTF-Tutorials/ was already a "live" view of the actual content, and this worked without specific directory namings - at least, according to https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site and my test at https://javagl.github.io/glTF-Tutorials/gltfTutorial/ ...)

But if this has advantages, I'm fine with merging it.

**Comment by outofcontrol** [comment]
According to the page you reference, they are suggesting all files be in a /docs folder at the root of the repository. At first I wasn't sure if /docs was a suggestion, however, it was the only choice to publish a folder from within this repository. It is possible I am not understanding something here. 

image

Your test works well, but it shows glTF-Tutorials/gltfTutorial, and we want to get it into a root folder of our choosing at /gltf/tutorials. Moving to /docs seems to accomplish this if we then alter the links to point to /gltf/tutorials/ instead of to /glTF-Tutorials.

**Comment by javagl** [comment]
<sup>(Sorry for the delay) </sup>

To my understanding, the suggestion with the `/docs` folder is for cases where the main repo contains the source code of a project, and *only* the dedicated `docs` folder should be used for generating the website. 

But here, all files are Markdown, and the whole repo should be published in its entirety (which seems to be accomplished by the first option, "Use the master branch..."). 

The reason for the `glTF-Tutorials/gltfTutorial` structure is that this repo was originally intended to host *multiple* tutorials. The `gltfTutorial` is supposed the "main", "introductory" tutorial. But there might be other tutorials added later, as in

    glTF-Tutorials
        gltfTutorial  : The current one with basic intro
        gltfImplementationX : Tutorial for implementing glTF in some programming language X
        gltfPbrRendering : PBR rendering with glTF
        ...

There are no specific plans for further tutorials yet (except for maybe https://github.com/KhronosGroup/glTF-Tutorials/issues/24 ). 

So one question is: Could such additional subfolders still be handled with the `/docs` approach? 

(I could imagine that this would make it necessary to ~"map some directories to other paths" in the same way that it is necessary *now*...)

**Comment by outofcontrol** [comment]
Unfortunately no time to pursue further so I've redirected all traffic from /gltf/tutorials to ttps://github.khronos.org/glTF-Tutorials/

**Pull request closed without merging**
